// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnmikeafphlqlimghzlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubWlrZWFmcGhscWxpbWdoemxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTA5NDQsImV4cCI6MjA2NjgyNjk0NH0.dgoRAFoNsJf1tCB67iGtJIdsaLO6al71oHiAtGdDiZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});